---
# name: Checks

# on: [push]

# jobs:
#   test-lint:
#     name: Test and Lint
#     runs-on: ubuntu-latest
#     steps:
#       - name: Login to Docker Hub
#         uses: docker/login-action@v1
#         with:
#           username: ${{ secrets.DOCKERHUB_USER }}
#           password: ${{ secrets.DOCKERHUB_TOKEN }}
#       - name: Checkout
#         uses: actions/checkout@v2
#       - name: Test
#         run: docker-compose run --rm app sh -c "python manage.py test"
#       - name: Lint
#         run: docker-compose run --rm app sh -c "flake8"

name: Checks

on: [push]

jobs:
  test-lint:
    name: Test and Lint
    runs-on: ubuntu-latest  # استفاده از آخرین نسخه اوبونتو
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Docker Compose v2
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose-plugin
          docker compose version  # نمایش نسخه نصب‌شده

      - name: Test
        run: docker compose run --rm app sh -c "python manage.py test"

      - name: Lint
        run: docker compose run --rm app sh -c "flake8"
